In [1]:
import numpy as np
import torch

In [2]:
# create vectors
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

# dot product via function
print(np.dot(nv1, nv2))

# dot product via computation
print(np.sum(nv1 * nv2))

-2
-2


Matrix Mult

In [3]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications
# @ is shorthand for np.matmul(A,B)
print(np.round( A @ B,  2))
print()
print(np.round( C.T @ A,  2))


[[ 2.72  3.1  -0.31 -0.56  2.25]
 [-2.61  0.68 -1.36 -2.31 -7.11]
 [-2.81 -1.95 -0.28 -0.05  1.86]]

[[ 0.24  2.16  1.31 -0.64]
 [-3.48  3.44  3.67  3.04]
 [ 0.01 -2.2  -1.51  0.4 ]
 [-2.81  2.99  1.85  2.7 ]
 [ 0.77  0.43 -0.71 -0.73]
 [ 0.52 -0.2  -0.76 -0.42]
 [ 3.05 -0.61 -5.46 -2.25]]


# Matrix Mult with Pytorch

In [4]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1, dtype=torch.float )

# try some multiplications
print(np.round( A @ B,  2)), print()
print(np.round( A @ C1, 2)), print()
print(np.round( A @ C2, 2))

tensor([[ 0.9700,  0.6000, -1.0000, -0.9800,  0.4700],
        [-1.9000,  0.4200,  1.9300,  0.8300,  1.0500],
        [ 0.6600, -3.4600, -3.0000,  3.0900,  2.7300]])

tensor([[ 0.9400, -1.4700,  0.0300,  0.3400, -0.6600, -0.3300, -0.7200],
        [-1.5200,  1.4200, -0.8300, -0.6600, -0.0900,  2.0900,  0.1800],
        [-0.6900,  1.9800, -1.4300,  3.7100,  3.7600, -0.8600, -0.1900]],
       dtype=torch.float64)

tensor([[ 0.9400, -1.4700,  0.0300,  0.3400, -0.6600, -0.3300, -0.7200],
        [-1.5200,  1.4200, -0.8300, -0.6600, -0.0900,  2.0900,  0.1800],
        [-0.6900,  1.9800, -1.4300,  3.7100,  3.7600, -0.8600, -0.1900]])
