In [1]:
import numpy as np
import torch

In [ ]:
# create vectors
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

# dot product via function
print(np.dot(nv1, nv2))

# dot product via computation
print(np.sum(nv1 * nv2))

Matrix Mult

In [ ]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications
# @ is shorthand for np.matmul(A,B)
print(np.round( A @ B,  2))
print()
print(np.round( C.T @ A,  2))


# Matrix Mult with Pytorch

In [12]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1, dtype=torch.float )

# try some multiplications
print(np.round( A @ B,  2)), print()
print(np.round( A @ C1, 2)), print()
print(np.round( A @ C2, 2))

tensor([[-1.4200, -1.6100, -1.2000, -2.4600, -0.7400],
        [-3.4800, -0.4300, -0.1300, -0.7000,  1.1700],
        [ 2.0600, -0.1000,  1.7300,  1.0100,  3.7000]])

tensor([[-0.9400,  0.2000,  1.2700, -0.9500,  1.4000,  0.4900, -0.0900],
        [-0.6500, -0.9000, -0.6100, -0.5300,  1.3000, -0.5900,  2.1600],
        [-0.7800,  0.9100,  1.5200,  0.4700,  4.7500, -3.1100, -0.6200]],
       dtype=torch.float64)

tensor([[-0.9400,  0.2000,  1.2700, -0.9500,  1.4000,  0.4900, -0.0900],
        [-0.6500, -0.9000, -0.6100, -0.5300,  1.3000, -0.5900,  2.1600],
        [-0.7800,  0.9100,  1.5200,  0.4700,  4.7500, -3.1100, -0.6200]])
