In [2]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
# create a vector
v = np.array([ 1,40,2,-3] )

# find and report the min/max values
minval = np.min(v)
maxval = np.max(v)
print('Min,max: %g,%g' %(minval,maxval))

# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)
print('argmin,argmax: %g,%g' %(minidx,maxidx))

Min,max: -3,40
argmin,argmax: 3,1


# With a Matrix

In [4]:
M = np.array([ [0,1,10],
               [20,8,5]
               ])
print(M), print()

# various minima in this matrix!
minvals1 = np.min(M)
minvals2 = np.min(M,axis=0)
minvals3 = np.min(M,axis=1)
print(f'Min of entire matrix: {minvals1}')
print(f'Min of each column: {minvals2}')
print(f'Min of each row: {minvals3}')

# argmin/max
minidx1 = np.argmin(M)
minidx2 = np.argmin(M,axis=0)
minidx3 = np.argmin(M,axis=1)

[[ 0  1 10]
 [20  8  5]]

Min of entire matrix: 0
Min of each column: [0 1 5]
Min of each row: [0 5]


# With PyTorch

In [5]:
v = torch.tensor( [ [ 1,40,2,-3], [20,3,5,8] ] )

minval = torch.min(v)
print('argmin(v): ' + str(minidx))

minval1 = torch.min(v,axis=0)
print(minval1.values)
print(minval1.indices)

argmin(v): 3
tensor([ 1,  3,  2, -3])
tensor([0, 1, 0, 0])
