In [5]:
import numpy as np
import torch

In [6]:
# create vectors
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])

# dot product via function
print(np.dot(nv1, nv2))

# dot product via computation
print(np.sum(nv1 * nv2))

-2
-2


Matrix Mult

In [7]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications
# @ is shorthand for np.matmul(A,B)
print(np.round( A @ B,  2))
print()
print(np.round( C.T @ A,  2))


[[ 1.05  1.64 -0.82 -1.9   1.99]
 [ 4.84 -0.85  2.77  0.98  0.35]
 [-0.52 -0.22  0.56  0.63 -0.88]]

[[ 1.66 -0.6   1.33  0.11]
 [ 1.27  1.29  0.68  0.31]
 [-2.64  1.85 -0.08 -0.55]
 [-0.38 -0.48 -1.07  0.09]
 [ 0.52 -1.9  -1.03  0.21]
 [-2.51  0.18 -1.48 -0.35]
 [-0.22 -0.43 -0.87  0.1 ]]


# Matrix Mult with Pytorch

In [8]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1, dtype=torch.float )

# try some multiplications
print(np.round( A @ B,  2)), print()
print(np.round( A @ C1, 2)), print()
print(np.round( A @ C2, 2))

tensor([[ 2.8800, -1.9600,  3.2100,  0.2000,  3.3900],
        [ 0.0800,  0.3800,  1.0400, -0.6100, -0.7500],
        [-0.8200,  0.3100,  1.1900,  0.4000,  0.4500]])

tensor([[-0.8800,  1.4600, -4.7800, -3.4400, -0.2600,  0.6900,  2.6600],
        [ 0.3800,  0.1000, -0.3300,  0.6600, -0.1900,  0.9000,  0.2500],
        [ 0.1600,  1.1900,  0.0900,  0.2900, -0.9000, -0.9100,  0.2000]],
       dtype=torch.float64)

tensor([[-0.8800,  1.4600, -4.7800, -3.4400, -0.2600,  0.6900,  2.6600],
        [ 0.3800,  0.1000, -0.3300,  0.6600, -0.1900,  0.9000,  0.2500],
        [ 0.1600,  1.1900,  0.0900,  0.2900, -0.9000, -0.9100,  0.2000]])
