In [5]:
import numpy as np
import torch

In [6]:
# transpose np arrays
nM = np.array([[1,2,3,4], [5,6,7,8]])
print(nM), print(' ')

# transpose it
print(nM.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [7]:
# using pytorch
tv = torch.tensor([ [ 1,2,3,4], [5,6,7,8] ])
print(tv), print(' ')

# transpose it
tvT = tv.T
print(tvT)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


In [8]:
# examine data types
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')

Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'torch.Tensor'>
